= Android Project Standards
v0.1, 2016-11-29

This document is a work in progress.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

= Git

== Location and Naming

The Nerdery SHALL use git, specifically bitbucket for all projects, unless otherwise
requested by a client. Projects MUST be placed under the client they are for
and project names MUST be written in the form of `mobile.{appName}.android` or
if a library `mobile.library.android.{libraryName}`. For example, the Hy-Vee
flagship application is named `mobile.flagship.android`. This convention is in
place so there is not confusion among the many projects that can be under a client
in BitBucket.

== Branching

The master branch is where the most up to date work is held. In the past a develop
branch has been recommend, but this has shown to cause confusion and many times
extra work being done, due to merges into the wrong branch. The master branch
MUST house the most up to date code, and all other branches be created from
master.

All work for a project MUST be completed on a separate branch. The branch SHALL
be named something descriptive about the work being done in the project.

To get the branch merged into the master branch a pull request SHALL be done
through the BitBucket UI and be reviewed by at least one other developer. The
reviewer SHOULD be the lead developer, unless they delegate this task out to
other team members. Consult with your lead for guidance on how they would like
the review process to go.

In addition to having a review, the branch MUST pass a merge build from CI.
This is a build that confirms that the code once merged into master will not
break the build.

== Forking

Although not required, it is RECOMMENDED to fork repositories under your user
account. This helps prevent clutter and reduces work for other developers trying
to always figure out what branches can and should be deleted. Under your own
fork you are in charge of all the branches and can delete and save them as you
see fit.

If using a fork you MUST set the 'Repository permissions' to allow the production
group to read. This allows any developer to access and see what you are working
on. Just in case you for get to create a PR before you go on vacation.

== Releases

All release builds MUST be tagged. The proper format for a tag would be
`v{major}.{minor}.{patch}`. Don't forget to push these to the remote (BitBucket).

An example would be:
```
git tag -a v1.0.0 # -a is not required but RECOMMENDED
git push origin v1.0.0
```

It is RECOMMENDED that before a release a release branch is made, so that bug
fixes can be merged into the release branch while new features can be included
in master.

== Commit History

=== Commit Message

We will follow ['The seven rules of a great Git commit message'](http://chris.beams.io/posts/git-commit/)

1. Separate subject from body with a blank line
1. Limit the subject line to 50 characters
1. Capitalize the subject line
1. Do not end the subject line with a period
1. Use the imperative mood in the subject line
1. Wrap the body at 72 characters
1. Use the body to explain what and why vs. how

When creating commit messages.

=== Clean History

To keep a clean commit history, which makes reviewing pull requests, and
rewinding code a much easier process. Commits on branches should be complete,
that is build, as well as follow The Seven Rules described above. The RECOMMENDED
solution to achieve this where many commits have been made during the
development process, is to use rebase to re-write history. Specifically use the
squash command.

= README

Every project MUST have a README file. The README MUST be a text file, this
file MAY use a markup language as long as it is easy to read with out the use
of a text processor. For example; plain text (.txt),
https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html[markdown] (.md), or
http://asciidoctor.org/[asciidoctor] (.adoc) would all be fine choices.

The README should contain all information possible about the project. It should
be the source of truth that will allow a developer to easily find anything
they need to know about the project. This should include but not limited to
links to JIRA, git, bamboo, documentation on how set up the project, and how
to release the project.

The following README template SHOULD be used for projects.

[README.md]
```
# Project Name

## Important Project links

<!--
Place important project links here, anything and everything that is related to
this project should be documented here.
-->

- [Project Page](https://mainframe.nerdery.com/project/page)
- [Source](https://git.nerdery.com/projects/PROJ/repos/cool.project/browse)
- [JIRA](https://issues.nerdery.com/projects/PROJ/summary)
- [Bamboo](https://builds.nerderylabs.com/browse/PROJ)
- [Buddy Build](https://dashboard.buddybuild.com/apps/1e5f9410f32f459aa9c3ca72a52cf6c1)
- [Fabric](https://fabric.io/android/apps/cool.project/)
- [Firebase](https://console.firebase.google.com/project/cool-project/overview)
- [Play Store](https://play.google.com/store/apps/details?id=cool.project.android)
- [Notes and Wires](https://drive.google.com/drive/u/1/folders/0B5j3shyAKaAnRks4b1hNY2kxWUE)

## Build Types
<!--
Give each build variant / flavor a different section here. Explain what each
does, why one would use it, what features each has, links to associated
services (ie. crashlytics, firebase), which should be given to clients, and what
signing keys are used.
-->

## Project Setup
<!--
Describe step by step setup and any dependancies that are required and
their setup as well.
-->

## In Scope Devices
<!--
List out devices that are in scope here.
-->

## Contributing
<!--
Include any special requirements for contributing to the project. Are there
special style guides that must be followed? Is there a different flow for
doing pull requests. Anything
-->
```

NOTE: The above is a guideline for creating a good README, but anything that
is though to be useful in a README should be included. Anything about a project
that differs from standard operating procedure SHOULD be documented in the
README.

= Testing

== Unit Testing

Unit Tests SHOULD be implemented for all code that does not have direct dependencies
on `android` packages and does some amount of work. That is basically any code
that is not in the views, fragments or activities, should be tested.
Not having the time to unit test is not a valid excuse for not testing. Time
is always saved in the long run when testing.

== UI Tests / Functional / Instrumentation Tests

All of these types of testing are RECOMMENDED, but should be considered on a
case by case basis to see if they fit for the project.

= CI

= Logging

Logging is very important in be able to quickly debug applications. For this
reason The Nerdery Android Developers have adopted
[Timber](https://github.com/JakeWharton/timber) as the logger of choice.
Timber allows to quickly log values to different streams instead of just logcat.
Timber also allows for what type of logging to be easily switched from build
type to build type.

The Nerdery SHOULD use Timber in all new projects, and is RECOMMENDED to be used
in legacy projects when the legacy project does not have a logging alternative
to logcat.

Release builds MUST NOT log to logcat. This is a security concern as well as a
performance issue. Logs SHOULD instead be sent to crashlytics, google analytics,
firebase, loggy, or some other comparable cloud logging option where they can
be reviewed and used to debug user issues.
