= Code Guidelines
include::include.adoc[]

== Kotlin Style Guides
The following style guides, in order, should be followed:

. Nerdery Code Guidelines
. https://android.github.io/kotlin-guides/style.html[Android Kotlin Style Guide]
. https://kotlinlang.org/docs/reference/coding-conventions.html[Kotlin Coding Conventions]

== Project structure

New projects should follow the Android Gradle project structure that is defined
on the https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/user-guide#TOC-Project-Structure[Android Gradle plugin user guide].
The https://github.com/rogues-dev/superglue[Super Glue Project Generator] is a
great starting point.

== File naming

=== Class files
Class names are written in http://en.wikipedia.org/wiki/CamelCase[UpperCamelCase].

For classes that extend an Android component, the name of the class should end
with the name of the component; for example: `SignInActivity`,
`SignInFragment`, `ImageUploaderService`, `ChangePasswordDialog`.

=== Resources files

Resources file names are written in __lowercase_underscore__.

==== Drawable files

Naming conventions for drawables:

|===
| Asset Type | Prefix | Example

| Action bar
| `ab_`
| `ab_stacked.9.png`

| Button
| `btn_`
| `btn_send_pressed.9.png`

| Dialog
| `dialog_`
| `dialog_top.9.png`

| Divider
| `divider_`
| `divider_horizontal.9.png`

| Icon
| `ic_`
| `ic_star.png`

| Menu
| `menu_`
| `menu_submenu_bg.9.png`

| Notification
| `notification_`
| `notification_bg.9.png`

| Tabs
| `tab_`
| `tab_pressed.9.png`

|===

Naming conventions for icons (taken from http://developer.android.com/design/style/iconography.html[Android iconography guidelines]):

|===
| Asset Type | Prefix | Example

| Icons
| `ic_`
| `ic_star.png`

| Launcher icons
| `ic_launcher`
| `ic_launcher_calendar.png`

| Menu icons and Action Bar icons
| `ic_menu`
| `ic_menu_archive.png`

| Status bar icons
| `ic_stat_notify`
| `ic_stat_notify_msg.png`

| Tab icons
| `ic_tab`
| `ic_tab_recent.png`

| Dialog icons
| `ic_dialog`
| `ic_dialog_info.png`

|===

Naming conventions for selector states:

|===
| State | Suffix | Example

| Normal
| `_normal`
| `btn_order_normal.9.png`

| Pressed
| `_pressed`
| `btn_order_pressed.9.png`

| Focused
| `_focused`
| `btn_order_focused.9.png`

| Disabled
| `_disabled`
| `btn_order_disabled.9.png`

| Selected
| `_selected`
| `btn_order_selected.9.png`

|===


==== Layout files

Layout files should match the name of the Android components that they are
intended for but moving the top level component name to the beginning. For
example, if we are creating a layout for the `SignInActivity`, the name of
the layout file should be `activity_sign_in.xml`.

|===
| Component | Class Name | Layout Name

| Activity
| `UserProfileActivity`
| `activity_user_profile.xml`

| Fragment
| `SignUpFragment`
| `fragment_sign_up.xml`

| Dialog
| `ChangePasswordDialog`
| `dialog_change_password.xml`

| AdapterView item
| ---
| `item_person.xml`

| Partial layout
| ---
| `partial_stats_bar.xml`

|===

A slightly different case is when we are creating a layout that is going to be
inflated by an `Adapter`, e.g to populate a `ListView`. In this case, the name
of the layout should start with `item_`.

Note that there are cases where these rules will not be possible to apply.
For example, when creating layout files that are intended to be part of other
layouts. In this case you should use the prefix `partial_`.

==== Menu files

Similar to layout files, menu files should match the name of the component.
For example, if we are defining a menu file that is going to be used in the
`UserActivity`, then the name of the file should be `activity_user.xml`

A good practice is to not include the word `menu` as part of the name because
these files are already located in the `menu` directory.

==== Values files

Resource files in the values folder should be __plural__, e.g. `strings.xml`,
`styles.xml`, `colors.xml`, `dimens.xml`, `attrs.xml`


== Language rules

These rules will be automatically applied by the link:../code-style/README.adoc[NerderyAndroid] codestyle.

=== Don't ignore exceptions

You must never do the following:

[source, kotlin]
----
fun setServerPort(value: String) {
    try {
        serverPort = Integer.parseInt(value)
    } catch (e: NumberFormatException) {
        // ...
    }
}
----

NOTE: While you may think that your code will never encounter this error condition
or that it is not important to handle it, ignoring exceptions like above
creates mines in your code for someone else to trip over some day. You must
handle every Exception in your code in some principled way. The specific
handling varies depending on the case. (https://source.android.com/source/code-style.html[Android code style guidelines])

See alternatives https://source.android.com/source/code-style#dont-ignore-exceptions[here].

=== Don't catch a single, generic Exception

You should not do this:

[source, kotlin]
----
try {
    someComplicatedIOFunction()        // may throw IOException
    someComplicatedParsingFunction()   // may throw ParsingException
    someComplicatedSecurityFunction()  // may throw SecurityException
    // phew, made it all the way
} catch (e: Exception) {                 // I'll just catch all exceptions
    handleError()                      // with one generic handler!
}
----

See the reason why and some alternatives
https://source.android.com/source/code-style.html#dont-catch-generic-exception[here].

=== Don't use finalizers

_We don't use finalizers. There are no guarantees as to when a finalizer will
be called, or even that it will be called at all. In most cases, you can do
what you need from a finalizer with good exception handling. If you absolutely
need it, define a `close()` method (or the like) and document exactly when that
method needs to be called. See `InputStream` for an example. In this case it is
appropriate but not required to print a short log message from the finalizer,
as long as it is not expected to flood the logs._
(https://source.android.com/source/code-style.html#dont-use-finalizers[Android code style guidelines])

TIP: Don't do it. If you absolutely must, first read and understand Effective
Java Item 7, "Avoid Finalizers," very carefully, and then don't do it.
https://google.github.io/styleguide/javaguide.html#s6.4-finalizers[Google Java Style Guide]

== Java style rules

=== Fields definition and naming

Fields should be defined at the __top of the file__, be final when possible,
private unless a constant (static final), and they should follow the
naming rules listed below.

* Fields start with a lower case letter.
* Do not use __m__ prefix.
* __s__ prefix may be used in situation where collisions/confusion between other
non-static variables may occur.
* Static final fields (constants) are ALL_CAPS_WITH_UNDERSCORES.

Example:

[source, kotlin]
----
class MyClass {
    val value = 0

    companion object {
        const val SOME_CONSTANT = 42
        private val sValue = 0f // Contrived but you get the point.
    }
}
----

=== Treat acronyms as words

|===
| Good | Bad

| `XmlHttpRequest`
| `XMLHTTPRequest`

| `getCustomerId`
| `getCustomerID`

| `String url`
| `String URL`

| `long id`
| `long ID`

|===

=== Use spaces for indentation

Use __4 space__ indents for blocks:

[source, kotlin]
----
if (x == 1) {
    x++
}
----

Use __8 space__ indents for line wraps:

[source, kotlin]
----
val i: Instrument =
        someLongExpression(that, wouldNotFit, on, one, line)
----

=== Brace style

Braces go on the same line as the code before them.

[source, kotlin]
----
class MyClass {
    fun func(): Int {
        if (something) {
            // ...
        } else if (somethingElse) {
            // ...
        } else {
            // ...
        }
    }
}
----

==== Statements

Braces around statements are required in most instances.

Typical case:

[source, kotlin]
----
if (condition) {
    body()
}
----

[source, kotlin]
----
if (condition)
    body()  // WRONG!
----

Braces are not required for `when` branches and `if` statement bodies if they meet BOTH
the following conditions:

. the conditional and the branch each contain at most a single predicate
. it fits on a single line

For `if` statements, there is an additional condition that there be no `else if` or `else`
branches.

[source, kotlin]
----
// Okay
if (string.isEmpty()) return

// Okay
when (value) {
    0 -> doSpecificThing()
    1 -> doAnotherSpecificThing()
	else -> doGenericThing()
}

// WRONG
if (string.isEmpty()) doEmptyThing() else doFullThing()

// STILL WRONG!
if (string.isEmpty()) doEmptyThing()
else doFullThing()

----

==== Expressions

An `if`/`else` conditional that is used as an expression may omit braces only if the
conditional and each branch of the expression contain at most a single predicate,
and the entire expression fits on one line.

[source, kotlin]
----
val value = if (string.isEmpty()) 0 else 1  // Okay
----

[source, kotlin]
----
val value = if (string.isEmpty())  // WRONG!
                0
            else
                1
----

[source, kotlin]
----
val value = if (string.isEmpty()) { // Okay
    0
} else {
    1
}
----

=== Annotations

==== Annotations practices

* @Deprecated: The @Deprecated annotation must be used whenever the use of the
annotated element is discouraged. If you use the @Deprecated annotation, you
must also have a comment naming an alternate implementation. In addition,
remember that a @Deprecated method is still supposed to work.

* @Override: The @Override annotation must be used whenever a method overrides
the declaration or implementation from a super-class.

* @SuppressWarnings: The @SuppressWarnings annotation should be used only under
circumstances where it is impossible to eliminate a warning. If a warning
passes this "impossible to eliminate" test, the @SuppressWarnings annotation
must be used, so as to ensure that all warnings reflect actual problems in the code.
When a @SuppressWarnings annotation is necessary, it must be prefixed with a
comment that explains the "impossible to eliminate" condition. This will
normally identify an offending class that has an awkward interface. For example:

[source, java]
----
// The third-party class com.third.useful.Utility.rotate() needs generics
@SuppressWarnings("generic-cast")
List<String> blix = Utility.rotate(blax);
----

==== Annotations style

__Classes, Methods and Constructors__

When annotations are applied to a class, method, or constructor, they are
listed after the documentation block and should appear as
__one annotation per line__ .

[source, java]
----
@SingleAnnoation
public class MySingleAnnotatedClass { }

/* This is the documentation block about the class */
@AnnotationA
@AnnotationB
public class MyAnnotatedClass { }
----

NOTE: Single annotations on methods may be inline with the method declaration.
This is especially helpful when inlining callbacks.

[source, java]
----
new MyCallBack() {
    @Override public void callback() {
      // implementation here
    }
}
----

__Fields__

Annotations applying to fields should be listed __on the same line__, unless
the line reaches the maximum line length.

[source, java]
----
@Nullable @Mock DataManager dataManager;
----

=== Limit variable scope

_The scope of local variables should be kept to a minimum
(Effective Java Item 29). By doing so, you increase the readability and
maintainability of your code and reduce the likelihood of error. Each variable
should be declared in the innermost block that encloses all uses of the
variable._

_Local variables should be declared at the point they are first used. Nearly
every local variable declaration should contain an initializer. If you don't
yet have enough information to initialize a variable sensibly, you should
postpone the declaration until you do._
(https://source.android.com/source/code-style.html#limit-variable-scope[Android code style guidelines])

=== Fully qualify imports

|===
| Good | Bad

|`import foo.Bar;`
|`import foo.*;`

|===

See more info https://source.android.com/source/code-style.html#fully-qualify-imports[here].

=== Order import statements

If you are using an IDE such as Android Studio, you don't have to worry about
this because your IDE is already obeying these rules. If not, have a look below.

The ordering of import statements is:

. Android imports
. Imports from third parties (com, net, org)
. java and javax
. junit
. Unconventional namespaces (butterknife, dagger, retrofit, etc.)
. Static imports

Example:

[source, kotlin]
----
import android.content.Intent
import android.os.Bundle
import android.support.annotation.Nullable
import android.support.v4.widget.SwipeRefreshLayout
import android.support.v7.app.ActionBar
import android.view.Menu
import android.view.View

import com.fernandocejas.arrow.optional.Optional
import com.squareup.moshi.Moshi

import net.domain.android.project.R

import java.util.List

import javax.inject.Inject

import butterknife.BindView
import butterknife.ButterKnife
import hugo.weaving.DebugLog
import rx.functions.Action0
import rx.subjects.Subject

import static android.view.View.VISIBLE
import static android.view.View.GONE
----

=== Logging guidelines

Use Jake Wharton's https://github.com/JakeWharton/timber[Timber] library for
logging.

Use the logging methods provided by the `Timber` class to print out error
messages or other information that may be useful for developers to identify
issues:

* `Timber.v(String message, Object... args)` (verbose)
* `Timber.d(String message, Object... args)` (debug)
* `Timber.i(String message, Object... args)` (information)
* `Timber.w(String message, Object... args)` (warning)
* `Timber.e(String message, Object... args)` (error)

To log exceptions use the overloaded versions
`Timber.*(Throwable t, String message, Object... args)`

All logs to logcat must be turned off for release builds. This can easily be
done with `Timber.plant(Tree)` method, and only planting the debug tree in
development builds.

It is recommended to have a `Tree` in release mode that will write logs
to crash reporting services such as Firebase or Crashlytics.

=== Class member ordering

There is no single correct solution for this but using a __logical__ and
__consistent__ order will improve code learnability and readability. It is
recommendable to use the following order:

. Constants
. Fields
. Constructors
. Overridden methods and callbacks
. Public methods
. Private methods
. Inner classes or interfaces

Example:

[source, kotlin]
----
class MainActivity : Activity() {

    private var title: String? = null
    private val textViewTitle: TextView? = null

    override fun onCreate() {
        // ...
    }

    fun setTitle(title: String) {
        this.title = title
    }

    private fun setUpView() {
        // ...
    }

    inner class AnInnerClass {
        // ...
    }
}
----

If your class is extending an __Android component__ such as an Activity or a
Fragment, it is a good practice to order the override methods so that they
__match the component's lifecycle__. For example, if you have an Activity that
implements `onCreate()`, `onDestroy()`, `onPause()` and `onResume()`, then the
correct order is:

[source, kotlin]
----
class MainActivity : Activity() {
    //Order matches Activity lifecycle
    public override fun onCreate(savedInstanceState: Bundle?) {}
    public override fun onResume() {}
    public override fun onPause() {}
    public override fun onDestroy() {}
}
----

=== Parameter ordering in methods

When programming for Android, it is quite common to define methods that take a
`Context`. If you are writing a method like this, then the __Context__ must be
the __first__ parameter.

The opposite case are __callback__ interfaces that should always be the __last__ parameter.

Examples:

[source, java]
----
// Context always goes first
fun loadUser(context: Context, userId: Int): User

// Callbacks always go last
fun loadUserAsync(context: Context, userId: Int, callback: UserCallback)
----

=== String constants, naming, and values

Many elements of the Android SDK such as `SharedPreferences`, `Bundle`, or
`Intent` use a key-value pair approach so it's very likely that even for a
small app you end up having to write a lot of String constants.

When using one of these components, you __must__ define the keys as
constant `static final` fields and they should be prefixed as indicated below. An
exception to this rule can be made if it is a single one time use key. Such as
using
https://github.com/JakeWharton/u2020/blob/master/src/internalDebug/java/com/jakewharton/u2020/data/DebugDataModule.java#L80[RxSharedPreferences with Dagger].

|===
| Element | Field Name Prefix

| SharedPreferences
| `PREF_`

| Bundle
| `BUNDLE_`

| Fragment Arguments
| `ARGUMENT_`

| Intent Extra
| `EXTRA_`

| Intent Action
| `ACTION_`

|===

NOTE: Note that the arguments of a Fragment - `Fragment.getArguments()` - are also a
Bundle. However, because this is a quite common use of Bundles, we define a
different prefix for them.

Example:

[source, kotlin]
----
companion object {
    // Note the value of the field is the same as the name to avoid duplication issues
    const val PREF_EMAIL = "PREF_EMAIL"
    const val BUNDLE_AGE = "BUNDLE_AGE"
    const val ARGUMENT_USER_ID = "ARGUMENT_USER_ID"

    // Intent-related items use full package name as value
    const val EXTRA_SURNAME = "com.myapp.extras.EXTRA_SURNAME"
    const val ACTION_OPEN_USER = "com.myapp.action.ACTION_OPEN_USER"
}
----

=== Arguments in Fragments and Activities

When data is passed into an `Activity` or `Fragment` via an `Intent` or a
`Bundle`, the keys for the different values __must__ follow the rules described
in the section above.

When an `Activity` or `Fragment` expects arguments, it should provide a
`public static` method that facilitates the creation of the relevant `Intent`
or `Fragment`.

In the case of Activities the method is usually called `newStartIntent()`:

[source, kotlin]
----
companion object {
    fun newStartIntent(context: Context, user: User): Intent {
        return Intent(context, ThisActivity::class.java).apply {
            putExtra("gdgads", user)
        }
    }
}
----

For Fragments it is named `newInstance()` and handles the creation of the
Fragment with the right arguments:

[source, kotlin]
----
companion object {
    fun newInstance(user: User) = UserFragment().apply {
        arguments = Bundle().apply {
            putParcelable(ARGUMENT_USER, user)
        }
    }
}
----

NOTE:  These methods should go at the top of the class before `onCreate()`. If we provide
the methods described above, the keys for extras and arguments should be `private` because
there is not need for them to be exposed outside the class.

=== Line length limit

Code lines should not exceed __120 characters__. If the line is longer than
this limit there are usually two options to reduce its length:

* Extract a local variable or method (preferable).
* Apply line-wrapping to divide a single line into multiple ones.

There are two __exceptions__ where it is possible to have lines longer than 120:

* Lines that are not possible to split, e.g. long URLs in comments.
* `package` and `import` statements.

==== Line-wrapping strategies

There isn't an exact formula that explains how to line-wrap and quite often
different solutions are valid. However there are a few rules that can be
applied to common cases.

__Break at operators__

When the line is broken at an operator, the break comes __before__ the
operator. For example:

[source, java]
----
int longName = anotherVeryLongVariable + anEvenLongerOne - thisRidiculousLongOne
        + theFinalOne;
----

__Assignment Operator Exception__

An exception to the `break at operators` rule is the assignment operator `=`,
where the line break should happen __after__ the operator.

[source, java]
----
int longName =
        anotherVeryLongVariable + anEvenLongerOne - thisRidiculousLongOne + theFinalOne;
----

__Method chain case__

When multiple methods are chained in the same line - for example when using
Builders - every call to a method should go in its own line, breaking the line
before the `.`

[source, kotlin]
----
Picasso.with(context).load("https://i.imgur.com/kG0deA5.jpg").into(imageView)
----

[source, kotlin]
----
Picasso.with(context)
        .load("https://i.imgur.com/kG0deA5.jpg")
        .into(imageView)
----

__Long parameters case__

When a method has many parameters or its parameters are very long, we should
break the line after every comma `,`

[source, kotlin]
----
loadPicture(context, "https://i.imgur.com/kG0deA5.jpg", imageViewProfilePicture, "Title of the picture", clickListener)
----

[source, kotlin]
----
loadPicture(context,
        "https://i.imgur.com/kG0deA5.jpg",
        imageViewProfilePicture,
        "Title of the picture",
        clickListener)
----

=== RxJava chains styling

Rx chains of operators require line-wrapping. Every operator must go in a new line and the line should be broken before the `.`

[source, kotlin]
----
fun syncLocations(): Observable<Location> {
    return databaseManager.getAllLocations()
            .concatMap { retrofitService.getLocation(it.id) }
            .retry { throwable is RetrofitError }
}

----

== XML style rules

=== Use self closing tags

When an XML element doesn't have any contents, you __must__ use self closing
tags. Self closing tag must go on a new line.

This is __good__:

[source, xml]
----
<TextView
    android:id="@+id/text_view_profile"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    />
----

This is __bad__ :

[source, xml]
----
<!-- Don\'t do this! -->
<TextView
    android:id="@+id/text_view_profile"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">
</TextView>
----

=== Resources naming

Resource IDs and names are written in __lowercase_underscore__.

==== ID naming

IDs should be suffixed with the name of the element in lowercase underscore.
With the exception of menu items, which should use a prefix.
For example:

|===
| Element | Prefix

| `TextView`
| `_text`

| `EditText`
| `_input`

| `ImageView`
| `_image`

| `Button`
| `_button`

| `Menu`
| `menu_`

|===

Image view example:

[source, xml]
----
<ImageView
    android:id="@+id/my_account_profile_image"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    />
----

Menu example:

[source, xml]
----
<menu>
    <item
        android:id="@+id/menu_done"
        android:title="Done"
        />
</menu>
----

==== Strings

String names start with a prefix that identifies the section they belong to.
For example `registration_email_hint` or `registration_name_hint`. If a
string __doesn't belong__ to any section, then you should follow the rules
below:

|===
| Prefix | Description

| `error_`
| An error message

| `msg_`
| A regular information message

| `title_` | A title, i.e. a dialog title

| `action_`
| An action such as "Save" or "Create"

|===

Think of reusing string resources as you would think of reusing custom views.
Make sure that the meaning/functionality is the same, or else duplicate the
string (i.e. two different buttons with the same copy that do different
things should have two different string resources) .

Organize your strings.xml into sections that each have a header describing
what part of the app it's for, such as <!-- Navigation Drawer --> or
<!-- Profile -->.

Be sure to mark strings that aren't intended for translation:
 http://tools.android.com/recent/non-translatablestrings[Android Docs]

==== Styles and Themes

Unless the rest of resources, style names are written in __UpperCamelCase__.

=== Attributes ordering

As a general rule you should try to group similar attributes together. A good
way of ordering the most common attributes is:

. XML namespace (if first tag in layout file)
. View ID
. Layout width and layout height
. Other layout attributes (sorted alphabetically)
. Remaining attributes (sorted alphabetically)
. Style/Theme

Example:

[source, xml]
----
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/item_row"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="16dp"
    android:animateLayoutChanges="true"
    android:clipChildren="false"
    style="@style/AppTheme.Recycler.Items.Row">
----

== Tests style rules

=== Unit tests

Test classes should match the name of the class the tests are targeting,
followed by `Test`. For example, if creating a test class that contains tests
for the `DatabaseManager`, it should named `DatabaseManagerTest`. If
Spock is being used the same rule applies but instead of 'Test', the 'Spec' suffix
should be used instead. Tests should be placed in the same package as the class
they are testing.

Test methods are annotated with `@Test` and should generally start with the
name of the method that is being tested, followed by a precondition and/or
expected behavior.

* Template: `@Test void methodNamePreconditionExpectedBehaviour()`
* Example: `@Test void signInWithEmptyEmailFails()`

Precondition and/or expected behavior may not always be required if the test
is clear enough without them.

Sometimes a class may contain a large amount of methods, that at the same
time require several tests for each method. In this case, it's recommendable to
split up the test class into multiple ones. For example, if the `DataManager`
contains a lot of methods we may want to divide it into
`DataManagerSignInTest`, `DataManagerLoadUsersTest`, etc. Generally you will
be able to see what tests belong together because they have common
https://en.wikipedia.org/wiki/Test_fixture[test fixtures].

=== Espresso tests

Every Espresso test class usually targets an Activity, therefore the name
should match the name of the targeted Activity followed by `Test`, e.g.
`SignInActivityTest`

When using the Espresso API it is a common practice to place chained methods in new lines.

[source, java]
----
onView(withId(R.id.view))
        .perform(scrollTo())
        .check(matches(isDisplayed()))
----
