= Android Project Standards
include::include.adoc[]

This is a living document. To request changes, please open a pull request.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

= Git

== Location and Naming

The Nerdery SHALL use git, specifically BitBucket Server for all projects unless otherwise
requested by a client. Projects MUST be placed under the client they are for
and project names MUST be written in the form of `mobile.{appName}.android`
(all lower case) or if a library project `mobile.library.android.{libraryName}`.
For example, the Hy-Vee flagship application is named `mobile.flagship.android`.
This convention is in place so there is not confusion among the many projects
that can be listed under a client in BitBucket.

== Branching

The **master** branch is where the most up to date work is held. In the past, a develop
branch had been used, but this has shown to cause confusion and many times
resulted in extra work.

All work for a project MUST be completed on a separate branch. The branch SHALL
be named something descriptive about the work being done in that branch.

To get the branch merged into the master branch a pull request SHALL be created
through the BitBucket UI and be reviewed by at least one other developer. The
reviewer SHOULD be the lead developer unless the lead developer delegates this
task out to other team members. Consult with your lead for guidance on how
they would like the review process to go.

In addition to having a review, the branch MUST pass a merge build from
<<Continuous Integration>>. This is a build that confirms that the code once
merged into master will not break the build.

== Forking

Although not required, it is RECOMMENDED to fork repositories under your user
account. This helps prevent clutter and reduces work for other developers trying
to always figure out what branches can and should be deleted. Under your own
fork, you are in charge of all the branches and can delete and save them as you
see fit.

IMPORTANT: If using a fork you MUST set the 'Repository Permissions' to allow
the production group to read. This allows any developer to access and see what
you are working on. Just in case you forget to create a PR before you go on
vacation.

== Releases

NOTE: A release is defined as the code that is currently or soon to be in the
Play Store.

All release builds MUST be tagged. The proper format for a tag would be
`v{major}.{minor}.{patch}`.

TIP: Don't forget to push the tags to the remote (BitBucket).

An example would be:
```
git tag -a v1.0.0 # -a is not required but RECOMMENDED
git push origin v1.0.0
```

It is RECOMMENDED that before creating a release, a release branch is created,
so that bug fixes can be merged into the release branch while new features can
be included in master. The release branch name SHOULD be
`release-{major}.{minor}.{patch}`

== Commit History

=== Commit Message

We will follow http://chris.beams.io/posts/git-commit/['The seven rules of a great Git commit message']
when creating commit messages. They are as follows.

. Separate subject from body with a blank line
. Limit the subject line to 50 characters
. Capitalize the subject line
. Do not end the subject line with a period
. Use the imperative mood in the subject line
. Wrap the body at 72 characters
. Use the body to explain what and why vs. how

=== Clean History

To keep a clean commit history, which makes reviewing pull requests, and
rewinding code a easier process, commits on branches SHOULD be complete,
that is buildable, as well as follow The Seven Rules described above. The RECOMMENDED
solution to achieve this is to use the `--amend` flag for committing when
making multiple edits to a branch or where many commits have already been made
during the development process use rebase command to re-write history.

= README

Every project MUST have a README file. The README MUST be a text file, this
file MAY use a markup language as long as it is easy to read without the use
of a text processor. For example; plain text (.txt),
https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html[markdown] (.md), or
http://asciidoctor.org/[asciidoctor] (.adoc) would all be fine choices.

The README should contain all information possible about the project. It should
be the source of truth that will allow a developer to easily find anything
they need to know about the project. This should include but is not limited to
links to JIRA, git, Buddy Build, documentation on how to set up the project,
and how to release the project.

The following README template SHOULD be used for projects.

[README.md]
```
# Project Name

## Important Project links

<!--
Place important project links here, anything and everything that is related to
this project should be documented here.
-->

- [Project Page](https://mainframe.nerdery.com/project/page)
- [Source](https://git.nerdery.com/projects/PROJ/repos/cool.project/browse)
- [JIRA](https://issues.nerdery.com/projects/PROJ/summary)
- [Bamboo](https://builds.nerderylabs.com/browse/PROJ)
- [Buddy Build](https://dashboard.buddybuild.com/apps/1e5f9410f32f459aa9c3ca72a52cf6c1)
- [Fabric](https://fabric.io/android/apps/cool.project/)
- [Firebase](https://console.firebase.google.com/project/cool-project/overview)
- [Play Store](https://play.google.com/store/apps/details?id=cool.project.android)
- [Notes and Wires](https://drive.google.com/drive/u/1/folders/0B5j3shyAKaAnRks4b1hNY2kxWUE)

## Build Types
<!--
Give each build variant/flavor a different section here. Explain what each
does, why one would use it, what features each has, links to associated
services (ie. crashlytics, firebase), which should be given to clients, and what
signing keys are used.
-->

## Project Setup
<!--
Describe step by step setup and any dependencies that are required and
their setup as well.
-->

## In Scope Devices
<!--
List out devices that are in scope here.
-->

## Contributing
<!--
Include any special requirements for contributing to the project. Are there
special style guides that must be followed? Is there a different flow for
doing pull requests. Anything else that might be relevant for contributing.
-->
```

NOTE: The above is a guideline for creating a good README, but anything that
is thought to be useful in a README should be included. Anything about a project
that differs from standard operating procedure SHOULD be documented in the
README.

= Testing

== Unit Testing

Unit Tests SHOULD be implemented for all code that does not have direct dependencies
on `android` packages and does some amount of work. That is any code
that is not in the views, fragments or activities, should be tested.
Not having the time to unit test is not a valid excuse for not testing. Time
is always saved in the long run when testing.

== UI Tests / Functional / Instrumentation Tests

All of these types of testing are RECOMMENDED, but should be considered on a
case by case basis to see if they fit for the project.

= Continuous Integration

All Android Projects at The Nerdery MUST use CI.
https://dashboard.buddybuild.com[Buddy Build] is a quick and
a convenient way to set these up with our BitBucket Server.

== Setting Up Buddy Build

. Create a ticket to http://nrdry.com/sisreq[SIS] to allow
Buddy Build to see your project. Buddy build
can not see projects by default to ensure our clients privacy. Projects with
specific security requirements may not be able to use Buddy Build. Check
with your project lead or project manager to ensure that you may use Buddy
Build.
. While you are waiting for your project to be exposed toBuddy Build follow
these directions to get your
http://docs.buddybuild.com/docs/connect-with-bitbucket-server[BitBucket Account integrated]
with Buddy Build.
. Once your project can be seen by Buddy Build, follow
http://docs.buddybuild.com/docs/selecting-an-app[these sets] to get
your project setup and built in buddy build.

NOTE: It is RECOMMENDED to let Buddy Build handle the building of your release
APKs and managing version numbers. This avoids confusion and ensures a single
place where every build will be built in the exact same way.

= Logging

Logging is very important in be able to quickly debug applications. For this
the reason The Nerdery Android Developers have adopted
https://github.com/JakeWharton/timber[Timber] as the logger of choice.
Timber allows to quickly log values to different streams instead of just logcat.
Timber also allows for the type of logging to be easily switched from build
type to build type.

The Nerdery SHOULD use Timber in all new projects and is RECOMMENDED to be used
in legacy projects when the legacy project does not have a logging alternative
to logcat.

Release builds MUST NOT log to logcat. This is a security concern as well as a
performance issue. Logs SHOULD instead be sent to crashlytics, google analytics,
firebase, loggy, or some other comparable cloud logging option where they can
be reviewed and used to debug issues.
